### PR TITLE
Update Czech language files

### PR DESCRIPTION
**Pull request by DemonioCZ**
Version 5.6

### CODE REVIEW

**Comment by DemonioCZ** [comment]
Ready for merge

**Comment by DemonioCZ** [comment]
I tryed to translate your theme with loco translate but it doesnt work. Translation of admin part doesnt show in administration.

**Comment by InoPlugs** [comment]
@DemonioCZ 

Thank you for contribute translation.

Please try to update to 5.6.2 - this should fix the problem in theme options page.

**Comment by DemonioCZ** [comment]
Hi, still in english. But I found avia_framework-cs_CZ.po file in wp-content/languages/themes/ and translating this file, translation finally apeare in admin

**Comment by InoPlugs** [comment]
I recieved this e-mail from user but do not see it here:

Hi, still in english. But I found avia_framework-cs_CZ.po file in wp-content/languages/themes/ and translating this file, translation finally apeare in admin

**Comment by DemonioCZ** [comment]
Sorry I deleted it because later it works. Changed the translation location from loco folder to system (in loco custom folder it doesnt work)

**Comment by InoPlugs** [comment]
Thanks for clarify and that it is working now. @DemonioCZ

**Pull request merged**
